from src.callbacks.tab_upload import init_callbacks_tab_upload
from src.callbacks.tab_view import init_callbacks_tab_view
from src.callbacks.tab_inspect import init_callbacks_tab_inspect
from src.callbacks.tab_graphs import init_callbacks_tab_graphs
